### ISSUE TITLE
Enable use of pre-commit for easy use in a git hook

### ISSUE THREAD

**Issue by thclark** [standard/standard#1541]
**What version of this package are you using?**
latest

**What problem do you want to solve?**
Easier use of standard within a git hook.

**What do you think is the correct solution to this problem?**
Use of the [pre-commit](https://pre-commit.com/) library, like prettier does [here](https://prettier.io/docs/en/precommit.html#option-4-precise-commitshttpsgithubcomjameshenryprecise-commits)

**Are you willing to submit a pull request to implement this change?**
Yes, I have a fork already doing it (see the only addition [here](https://github.com/thclark/standard/blob/master/.pre-commit-hooks.yaml) and am happy to submit a PR if someone tells me what branch to make it into.

I'll also need to update the relevant section of the docs, but that's no problem to add, as long as this suggestion is welcome.

Using my fork of standard, my `.pre-commit-config.yaml` files simply contain:
```
  - repo: https://github.com/thclark/standard
    rev: master
    hooks:
      - id: standard
```

**Comment by thclark** [comment]
OK, the above may not be necessary. There's an `eslint` hook already that can be specified to use the standard plugin.

```
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: master
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@latest
          - eslint-plugin-standard@latest
          - eslint-plugin-react-hooks@latest
          - eslint-config-react-app@latest
          - eslint-plugin-react@latest
          - eslint-plugin-import@latest
          - eslint-plugin-flowtype@latest
          - eslint-plugin-jsx-a11y@latest
```

Will apply all the standard rules without maintaining a standard-only hook here.

But, it might be a nice-to-have. Any thoughts? @maintainers feel free to close if this is noise at this point.
